ft(create):create post with an image
ShemaM/My-Brand pull request #24
Opened 2020-12-08 06:05 UTC by ShemaM

#### What does this PR do?
> create a route to create a post with an  image
#### Description of Task to be completed
> installed `express-fileupload ` to upload image
> installed and configured `cloudinary` to store the image
> created controller class to manage crud related for blog post
#### How should this be manually tested?
>clone this repo `https://github.com/ShemaM/My-Brand.git`
> git checkout `ft-api-createPost`
> npm run dev
> got to postman run `POST localhost:3000/shema/blog`
> got format data attach `Author`, `Title`, `Content`, `image`
#### Any background context you want to provide?
>N/A
#### What are the relevant Trello story?
>https://trello.com/b/MQ9S1EBE/shemachristian

#### Screenshots (if appropriate)
><img width="1440" alt="Screen Shot 2020-12-07 at 22 24 47" src="https://user-images.githubusercontent.com/53241063/101446319-be0f9000-392b-11eb-8829-81349ea54bb5.png">

2020-12-09 08:11 UTC, habinezadalvan commented on server/src/config/db.js
> +console.log(process.env.NODE_ENV);
Please remove this unnecessary console.log

2020-12-09 08:12 UTC, habinezadalvan commented on server/src/_data/blog.json
> +    {
Please remove these dummy data

2020-12-09 08:13 UTC, habinezadalvan commented on server/src/controllers/blog.js
> +class blog {
I think it's better to start classes with Capital letter

2020-12-09 08:20 UTC, habinezadalvan commented on server/src/modal/blog.js
> +
I would suggest creating a validating middleware.

2020-12-09 08:21 UTC, habinezadalvan requested changes
Please work on the comments below.

2020-12-09 08:21 UTC, habinezadalvan reviewed
work on the comments

2020-12-09 08:22 UTC, habinezadalvan reviewed
Work on the comment below

2020-12-09 08:23 UTC, habinezadalvan reviewed
Work on the comments below

2020-12-10 06:47 UTC, ShemaM commented on server/src/controllers/blog.js
> +class blog {
yeah i have started class with capital letter

2020-12-10 06:48 UTC, ShemaM commented on server/src/_data/blog.json
> +    {
all dummy data removed

2020-12-10 06:48 UTC, ShemaM commented on server/src/modal/blog.js
> +
i have used joi validator

2020-12-10 06:48 UTC, ShemaM commented on server/src/config/db.js
> +console.log(process.env.NODE_ENV);
all unnecessary console.log i removed them

2020-12-10 08:31 UTC, merged